name: Trigger auto deployment for cont1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'run/helloworld/**'
    - '.github/workflows/cont1-AutoDeployTrigger-08ecbb89-6655-4648-97ca-c11247c292d1.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONT1_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}run/helloworld 
          registryUrl: micontain.azurecr.io
          registryUsername: ${{ secrets.CONT1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONT1_REGISTRY_PASSWORD }}
          containerAppName: cont1
          resourceGroup: res1
          imageToBuild: micontain.azurecr.io/cont1:${{ github.sha }}
          dockerfilePath: Dockerfile

     

